apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "{{.Values.app.name}}-hpa"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: {{ .Values.app.name }}
    apiVersion: "apps/v1"
  minReplicas: {{ .Values.hpa.min_replicas }}
  maxReplicas: {{ .Values.hpa.max_replicas }}
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80