apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
